#ifndef ASM_CONTEXT_SWITCH_OFFSETS
#define ASM_CONTEXT_SWITCH_OFFSETS

#define CONTEXT_SWITCH_STACK_SPACE_ALLOCATION (4 * 8)

#define CONTEXT_SWITCH_STACK_TEMP_REGISTER_BUFFER_OFFSET 0
#define CONTEXT_SWITCH_STACK_KERNEL_SATP_OFFSET 8
#define CONTEXT_SWITCH_STACK_KERNEL_GP_OFFSET 16
#define CONTEXT_SWITCH_STACK_TRAP_HANDLER_ADDRESS_OFFSET 24

#endif /* ASM_CONTEXT_SWITCH_OFFSETS */
