title: selfie
description: An educational software system of a tiny self-compiling C compiler, a tiny self-executing RISC-V emulator, and a tiny self-hosting RISC-V hypervisor.
google_analytics: UA-3827654-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions

collections:
  redirects:
    output: true

defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect